#!/bin/bash

# Make a git clone of *latest* upstream kkomelin/sui-explorer
#
# ***Careful*** overwrites everything under ~/suibase/typescript/sui-explorer
#
# The destination directory supports edit/push with kkomelin repos, while still being
# served by suibase-daemon.

EXPLORER_DEST_DIR="$HOME/suibase/typescript"
rm -rf "$EXPLORER_DEST_DIR/sui-explorer"
mkdir -p "$EXPLORER_DEST_DIR/sui-explorer"
cd "$EXPLORER_DEST_DIR" || exit 1
git clone https://github.com/kkomelin/sui-explorer.git --depth 1



