#!/bin/bash

# This is not normally called, only when suspecting that the
# suibase-daemon is not responding.
#

# Source '__globals.sh'.
SUIBASE_DIR="$HOME/suibase"
SCRIPT_COMMON_CALLER="$(readlink -f "$0")"
WORKDIR="none"

main() {
  # Detect if suibase is not installed!
  if [ ! -d "$SUIBASE_DIR" ]; then
    echo "ERROR: suibase is not installed! Check https://suibase.io/how-to/install"
    exit 1
  fi

  # shellcheck source=SCRIPTDIR/scripts/common/__globals.sh
  source "$SUIBASE_DIR/scripts/common/__globals.sh" "$SCRIPT_COMMON_CALLER" "$WORKDIR"
  trap cleanup EXIT

  # shellcheck source=SCRIPTDIR/scripts/common/__apps.sh
  source "$SUIBASE_DIR/scripts/common/__apps.sh"

  # shellcheck source=SCRIPTDIR/scripts/common/__suibase-daemon.sh
  source "$SUIBASE_DIR/scripts/common/__suibase-daemon.sh"

  exit_if_not_installed
  exit_if_deps_missing

  # Block users from running any concurrent CLI commands.
  cli_mutex_lock "suibase_daemon"


  update_SUIBASE_DAEMON_PID_var

  local _OLD_PID=$SUIBASE_DAEMON_PID
  start_suibase_daemon_as_needed

  if [ "$_OLD_PID" == "$SUIBASE_DAEMON_PID" ]; then
    restart_suibase_daemon
    # Check that the sui client responds for any workdir, except for localnet.
    wait_for_sui_client_up "exclude-localnet"
  fi
}

main "$@"
