#!/bin/bash

# This is not normally called, only when suspecting that the
# suibase-daemon is not responding.
#

# Source '__globals.sh'.
SUIBASE_DIR="$HOME/suibase"
SCRIPT_COMMON_CALLER="$(readlink -f "$0")"
WORKDIR="localnet"

main() {
  # Detect if suibase is not installed!
  if [ ! -d "$SUIBASE_DIR" ]; then
    echo "ERROR: suibase is not installed! Check https://suibase.io/how-to/install"
    exit 1
  fi

  # shellcheck source=SCRIPTDIR/scripts/common/__globals.sh
  source "$SUIBASE_DIR/scripts/common/__globals.sh" "$SCRIPT_COMMON_CALLER" "$WORKDIR"
  trap cleanup EXIT

  # shellcheck source=SCRIPTDIR/scripts/common/__suibase-daemon.sh
  source "$SUIBASE_DIR/scripts/common/__suibase-daemon.sh"

  exit_if_not_installed
  exit_if_deps_missing

  # Block users from running any concurrent CLI commands.
  cli_mutex_lock "localnet"
  cli_mutex_lock "mainnet"
  cli_mutex_lock "devnet"
  cli_mutex_lock "testnet"
  cli_mutex_lock "cargobin"
  cli_mutex_lock "active"

  restart_suibase_daemon
  # Check for any JSON-RPC up, except for localnet.
  wait_for_json_rpc_up "exclude-localnet"
}

main "$@"
