#!/bin/bash

# This script control this "workdir".
#
# You use 'workdir-exec' in the same way you would use 'localnet', 'devnet' suibase scripts...
#
# Example:
#    'localnet start' is equivalent to
#    '~/suibase/workdirs/localnet/workdir-exec start'
#
# Never move this script outside of its workdir. It must stay here to run
# within its intended context.

# Implementation details:
#   Initialize which context to use (with WORKDIR)
#   The WORKDIR variable is the directory name of *this* script location.
#   (e.g. localnet, devnet, cargobin etc...)
SCRIPT_COMMON_CALLER="$(readlink -f "$0")"
WORKDIR="$(basename "$(dirname "$SCRIPT_COMMON_CALLER")")"
# shellcheck source=SCRIPTDIR/../common/__globals.sh
source "$HOME/suibase/scripts/common/__globals.sh" "$SCRIPT_COMMON_CALLER" "$WORKDIR"

# Call the common code that can handle all the possible context.
# shellcheck source=SCRIPTDIR/../common/__workdir-exec.sh
source "$HOME/suibase/scripts/common/__workdir-exec.sh"
workdir_exec "$@"
