contexts:
  testnet:
    # module: site
    # portal: wal.app
    package: 0xf99aee9f21493e1590e7e5a9aea6f343a1f381031a04a732724871fc294be799
    general:
      rpc_url: https://fullnode.testnet.sui.io:443
      wallet: $HOME/suibase/workdirs/testnet/config-default/client.yaml
      walrus_binary: $HOME/suibase/workdirs/testnet/bin/walrus
      walrus_config: $HOME/suibase/workdirs/testnet/config-default/walrus-config.yaml
    #   gas_budget: 500000000
default_context: testnet
