[package]
name = "walrus_subsidies"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.73.0" }
WAL = { local = "../wal" }
Walrus = { local = "../walrus" }

[addresses]
walrus_subsidies = "0x0"
