contexts:
  testnet:
    # module: site
    # portal: wal.app
    package: 0xf99aee9f21493e1590e7e5a9aea6f343a1f381031a04a732724871fc294be799
    # general:
    #   rpc_url: https://fullnode.testnet.sui.io:443
    #   wallet: /path/to/.sui/sui_config/client.yaml
    #   walrus_binary: /path/to/walrus
    #   walrus_config: /path/to/testnet/client_config.yaml
    #   gas_budget: 500000000
  mainnet:
    # module: site
    # portal: wal.app
    package: 0x26eb7ee8688da02c5f671679524e379f0b837a12f1d1d799f255b7eea260ad27
    # general:
    #   rpc_url: https://fullnode.mainnet.sui.io:443
    #   wallet: /path/to/.sui/sui_config/client.yaml
    #   walrus_binary: /path/to/walrus
    #   walrus_config: /path/to/mainnet/client_config.yaml
    #   gas_budget: 500000000

default_context: mainnet
