contexts:
  mainnet:
    # module: site
    # portal: wal.app
    package: 0xfa65cb2d62f4d39e60346fb7d501c12538ca2bbc646eaa37ece2aec5f897814e
    general:
      rpc_url: https://fullnode.mainnet.sui.io:443
      wallet: $HOME/suibase/workdirs/mainnet/config-default/client.yaml
      walrus_binary: $HOME/suibase/workdirs/mainnet/bin/walrus
      walrus_config: $HOME/suibase/workdirs/mainnet/config-default/walrus-config.yaml
    #   gas_budget: 500000000
default_context: mainnet
