contexts:
  mainnet:
    system_object: 0x2134d52768ea07e8c43570ef975eb3e4c27a39fa6396bef985b5abc58d03ddd2
    staking_object: 0x10b9d30c28448939ce6c4d6c6e0ffce4a7f8a4ada8248bdad09ef8b70e4a3904
    subsidies_object: 0xb606eb177899edc2130c93bf65985af7ec959a2755dc126c953755e59324209e
    exchange_objects: []
    wallet_config:
      path: $HOME/suibase/workdirs/mainnet/config/client.yaml
      active_env: mainnet
    rpc_urls:
      - http://localhost:44343
      - https://fullnode.mainnet.sui.io:443
default_context: mainnet
