name: Detect Changes
description: Defines variables indicating the parts of the code that changed
outputs:
  isDoc:
    description: True when changes related to documentation
    value: "${{ steps.diff.outputs.isDoc }}"
  isRust:
    description: True when changes related to Rust
    value: "${{ steps.diff.outputs.isRust }}"
  isMove:
    description: True when changes related to Move
    value: "${{ steps.diff.outputs.isMove }}"
  isScript:
    description: True when changes related suibase scripts
    value: "${{ steps.diff.outputs.isScript }}"
  isDocHelperAPI:
    description: True when changes to Helper API (docs)
    value: "${{ steps.diff.outputs.isDoc }}"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Detect Changes
      uses: dorny/paths-filter@v2.11.1
      id: diff
      with:
        filters: |
          isRust:
            - 'crates/**'
            - '.github/workflows/rust.yml'
          isDoc:
            - 'docs/**'
            - '*.md'
            - '.github/workflows/deploy-docs.yml'
          isMove:
            - 'move/sources/**'
            - 'Move.toml'
          isScript:
            - 'scripts/**'
            - 'install'
            - 'uninstall'
            - 'update'
            - '.github/workflows/scripts-tests.yml'
          isDocHelperAPI:
            - 'rust/helper/lib.rs'
            - 'rust/helper/error.rs'
            - '.github/workflows/trig-ext-repos.yml'
