name: Detect Changes
description: Variables indicating the type of change to the repos

outputs:
  isDoc:
    description: True when changes related to docs/website.
    value: "${{ steps.diff.outputs.isDoc }}"
  isRust:
    description: True when changes related to Rust.
    value: "${{ steps.diff.outputs.isRust }}"
  isMove:
    description: True when changes related to Move
    value: "${{ steps.diff.outputs.isMove }}"
  isScript:
    description: True when changes related suibase scripts
    value: "${{ steps.diff.outputs.isScript }}"
  isDocHelperAPI:
    description: True when changes to Helper API (docs)
    value: "${{ steps.diff.outputs.isDocHelperAPI }}"
  isSuibaseDaemon:
    description: True when changes to Suibase Daemon
    value: "${{ steps.diff.outputs.isSuibaseDaemon }}"
  isVSCodeExtension:
    description: True when changes to Suibase VSCode extension
    value: "${{ steps.diff.outputs.isVSCodeExtension }}"

runs:
  using: composite
  steps:
    - name: Detect Changes
      uses: dorny/paths-filter@v3.0.2
      id: diff
      with:
        base: ${{ github.ref }}
        filters: |
          isRust:
            - 'rust/**'
          isDoc:
            - 'docs/**'
            - 'README.md'
            - '.github/workflows/deploy-docs.yml'
          isMove:
            - 'move/sources/**'
            - 'Move.toml'
          isScript:
            - 'scripts/**'
            - 'install'
            - 'uninstall'
            - 'update'
            - 'repair'
            - 'pip-install'
            - 'update-daemon'
            - 'restart'
            - '.github/workflows/scripts-tests.yml'
          isDocHelperAPI:
            - 'rust/helper/lib.rs'
            - 'rust/helper/error.rs'
            - '.github/workflows/trig-rust-api-docs.yml'
          isSuibaseDaemon:
            - 'rust/suibase/**'
            - '.github/workflows/trig-sui-binaries.yml'
          isVSCodeExtension::
            - 'typescript/vscode-extension/**'
