#!/bin/bash

# This script simply forward the command line to the proper sui-base script
# that was selected to be active (e.g. 'localnet set-active').
#
# The end result is the proper Sui binary (provided by Mysten) will
# eventually get called.
#
# So, you use 'asui' in the same way you would use 'sui' from Mysten. Example:
#    'asui client gas'
#
# One convenience is you do not have to specify the --client.config,
# , --network.config and --keystore-path options on the command line.
#

# Source 'sui-base/__script-common'.
SCRIPT_COMMON_CALLER="$(readlink -f "$0")"
WORKDIR="active"
source "$HOME/sui-base/scripts/__script-common" "$SCRIPT_COMMON_CALLER" "$WORKDIR"

# Trap the case of doing just a self-test for installation.
if [[ "$1" == "sui-base-script-name" ]]; then
  # This also test if the sourced "script_common" works ($SUI_SCRIPT should be "asui")
  echo "$SUI_SCRIPT"
  exit
fi

# Now we can use the same functions as all the other scripts.
update_ACTIVE_WORKDIR_var;

case "$ACTIVE_WORKDIR" in
    "localnet") lsui "$@" ;;
    "devnet") dsui "$@" ;;
    "testnet") tsui "$@" ;;
    *)
    echo "No active workdir was set (e.g. 'localnet set-active')";
    exit ;;
esac
