#!/bin/bash

# Script to create and control a Sui local network.

SUIBASE_DIR="$HOME/suibase"
if [ -d "$HOME/sui-base" ] && [ ! -d "$SUIBASE_DIR" ]; then
  if [ $# -eq 0 ]; then
    # This is to handle a rare and unlikely case where "update" would call localnet to get
    # the version upon ~/sui-base/update but localnet is not yet "suibase renamed". We cheat
    # a bit here by returning a dummy version without further involving any logic.
    echo "localnet suibase renamed required"
    echo "Do ~/sui-base/repair"
  else
    # Save the day. Do the one-time sui-base to suibase renaming.
    ("$HOME/sui-base/repair")
  fi
  exit 1
fi

# Source '__globals.sh'.
SCRIPT_COMMON_CALLER="$(readlink -f "$0")"
WORKDIR="localnet"
# shellcheck source=SCRIPTDIR/common/__globals.sh
source "$SUIBASE_DIR/scripts/common/__globals.sh" "$SCRIPT_COMMON_CALLER" "$WORKDIR"

exit_if_not_installed;

# Trap the case of doing just a self-test for installation.
if [[ "$1" == "suibase-script-name" ]]; then
  # This also test if the sourced "globals" works ($SCRIPT_NAME should be "localnet")
  echo "$SCRIPT_NAME"
  exit
fi

# shellcheck source=SCRIPTDIR/common/__globals.sh
source "$SUIBASE_DIR/scripts/common/__workdir-exec.sh"
workdir_exec "$@"
