#!/bin/bash

# This script simply call the proper sui binary (provided by Mysten Lab) and config that match
# the binary running for your localnet.
#
# Your localnet should have been installed when you did "localnet start".
#
# You use 'lsui' in the same way you would use 'sui' from Mysten. Example:
#    'lsui client gas'
#
# One convenience is you do not have to specify the --client.config,
# , --network.config and --keystore-path options on the command line.
#

# Source '__globals.sh'.
SCRIPT_COMMON_CALLER="$(readlink -f "$0")"
WORKDIR="localnet"
source "$HOME/sui-base/scripts/common/__globals.sh" "$SCRIPT_COMMON_CALLER" "$WORKDIR"

# Trap the case of doing just a self-test for installation.
if [[ "$1" == "sui-base-script-name" ]]; then
  # This also test if the sourced "globals" works.
  echo "$SUI_SCRIPT"
  exit
fi

sui_exec "$@"