#[derive(Debug, thiserror::Error)]
#[allow(clippy::large_enum_variant)]
pub enum SuiBaseError {
    /************************************************************/
    // API caller errors (e.g. doing things in wrong order)
    /************************************************************/
    #[error("sui-base: Not installed. Need to run ~/sui-base/install")]
    NotInstalled,

    #[error("sui-base: Workdir not selected. Successful call to `select_workdir` needed")]
    WorkdirNotSelected,

    #[error(
        "sui-base: Path could not be access. Check sui-base is selecting a valid active workdir"
    )]
    WorkdirAccessError,

    #[error(
        "sui-base: Workdir does not exists. Check sui-base is selecting a valid active workdir"
    )]
    WorkdirNotExists,

    #[error("sui-base: Not finding keystore `{path:?}`. Run the sui client to create it?")]
    SuiBaseKeystoreNotExists { path: String },

    #[error("sui-base: No published data found for package `{package_name:?}`. Did you do `{workdir:?}` publish?")]
    PublishedDataNotFound {
        package_name: String,
        workdir: String,
    },

    #[error("sui-base: missing link definition. Check sui-base.yaml links section.")]
    MissingLinkDefinition,

    #[error("sui-base: missing at least one link definition. Check sui-base.yaml links section.")]
    MissingAtLeastOneLinkDefinition,

    #[error("sui-base: missing `{url_field:?}` link field. May be a problem with the sui-base.yaml link section (1).")]
    MissingLinkField { url_field: String },

    /*****************************/
    // API bad parameter errors.
    /*****************************/
    #[error("sui-base: Invalid workdir name (empty string)")]
    WorkdirNameEmpty,

    #[error("sui-base: Invalid package name (empty string)")]
    PackageNameEmpty,

    #[error("sui-base: Invalid address name (empty string)")]
    AddressNameEmpty,

    #[error("sui-base: Invalid object_type parameter with missing field")]
    ObjectTypeMissingField,

    #[error("sui-base: Invalid object_type parameter")]
    ObjectTypeInvalidFormat,

    #[error("sui-base: not finding address name'{address_name:?}'")]
    AddressNameNotFound { address_name: String },

    /*****************************/
    // Sui-Base filesystem related errors
    //
    // Should not normally happen. Relates to files generated by sui-base, so could
    // be either a bug or abnormal termination while the file was being written.
    /*****************************/
    #[error("sui-base: Active workdir read of .state/name failed. Try to 'update' the workdir")]
    WorkdirStateNameAccessFailed,

    #[error("sui-base: Could not open DNS (client address) file `{path:?}`. Try to 'update' the workdir")]
    WorkdirStateDNSAccessFailed { path: String },

    #[error("sui-base: Active workdir .state/name not set. Try to 'update' the workdir")]
    WorkdirStateNameNotSet,

    #[error("sui-base: Invalid package-id.json format")]
    PackageIdJsonInvalidFormat,

    #[error("sui-base: Invalid package id hexadecimal `{id:?}`.")]
    PackageIdInvalidHex { id: String },

    #[error("sui-base: Could not read published new objects file `{path:?}`")]
    PublishedNewObjectReadError { path: String },

    #[error("sui-base: Could not parse published new objects id `{id:?}` from file `{path:?}`")]
    PublishedNewObjectParseError { path: String, id: String },

    #[error(
        "sui-base: workdir not fully initialized. Do '{workdir:?} start' or '{workdir:?} update'"
    )]
    WorkdirInitializationIncomplete { workdir: String },

    #[error("sui-base: Could not read dns file `{path:?}`")]
    WorkdirStateDNSReadError { path: String },

    #[error("sui-base: Could not parse dns address `{address:?}` from file `{path:?}`")]
    WorkdirStateDNSParseError { path: String, address: String },

    #[error("sui-base: Could not open published data `{path:?}`. Was the package published with success?")]
    PublishedDataAccessError { path: String },

    #[error("sui-base: Could not open published new objects file `{path:?}`. Was the package published with success?")]
    PublishedNewObjectAccessError { path: String },

    #[error("sui-base: Could not read link file `{path:?}`")]
    WorkdirStateLinkReadError { path: String },

    /*****************************/
    // Sui-Base internal errors
    // Likely a bug in sui-base code.
    /*****************************/
    #[error("sui-base: Workdir name not set. Internal error. Contact developer")]
    WorkdirNameNotSet,

    #[error("sui-base: Workdir path not set. Internal error. Contact developer")]
    WorkdirPathNotSet,

    #[error("sui-base: Invalid file name (empty string)")]
    FileNameEmpty,

    #[error("sui-base: Invalid state name (empty string)")]
    StateNameEmpty,
}
