#!/bin/bash

SUIBASE_DIR="$HOME/suibase"
WORKDIR="none"

# shellcheck source=SCRIPTDIR/scripts/common/__suibase-daemon.sh
source "$SUIBASE_DIR/scripts/common/__globals.sh" "$SCRIPT_COMMON_CALLER" "$WORKDIR"
trap cleanup EXIT

# shellcheck source=SCRIPTDIR/scripts/common/__globals.sh
source "$SUIBASE_DIR/scripts/common/__suibase-daemon.sh"

# Force stop the daemon.
rm "$SUIBASE_DIR/workdirs/common/bin/suibase-daemon" >/dev/null 2>&1
PID=$(lsof /tmp/.suibase/suibase-daemon.lock 2>/dev/null | grep "^suibase-d " | while read c1 c2 c3; do echo $c2; done)
if [ -n "$PID" ]; then
  kill -s SIGTERM $PID
fi

update_suibase_daemon_and_start
wait_for_json_rpc_up "any"
