#!/bin/bash

SUIBASE_DIR="$HOME/suibase"
WORKDIR="none"

# shellcheck source=SCRIPTDIR/../common/__suibase-daemon.sh
source "$SUIBASE_DIR/scripts/common/__globals.sh" "$SCRIPT_COMMON_CALLER" "$WORKDIR"
trap cleanup EXIT

# shellcheck source=SCRIPTDIR/../common/__globals.sh
source "$SUIBASE_DIR/scripts/common/__suibase-daemon.sh"

# Force stop the daemon.
rm "$SUIBASE_DIR/workdirs/common/bin/suibase-daemon" >/dev/null 2>&1
update_SUIBASE_DAEMON_PID_var
if [ -n "$SUIBASE_DAEMON_PID" ]; then
  kill -s SIGTERM "$SUIBASE_DAEMON_PID"
fi

update_suibase_daemon_and_start
wait_for_json_rpc_up "any"
