################################################################
# Adding new content?
#
# Scroll-down and add your ".md" file to the ".nav" section.
#
# Try to not touch the rest...
#
################################################################

site_name: sui-base.io
site_author: Sui Community
site_description: >-
  Sui-Base an open-source development enviroment and documentation project for the Sui network

docs_dir: "website"

# Repository
repo_name: sui-base
repo_url: https://github.com/sui-base/sui-base

theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.footer
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
#extra:
#  alternate:
#    - name: English
#      link: /en/
#      lang: en
#    - name: French
#      link: /fr/
#      lang: fr

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  #- toc:
  #    permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  #- pymdownx.magiclink:
  #    repo_url_shorthand: true
  #    user: squidfunk
  #    repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true

##########################################################################
# Adding new content to the cookbook?
#
# Please add your '.md' in the "Sui Cookbook" section, and thank you.
#
# Indentation matter (to make your file be under the correct subject).
#
##########################################################################
nav:
  - "Sui Cookbook":
      - "Getting Started":
          - "Introduction": cookbook.md
          - "Sui Installation": cookbook/sui-install.md

      - "Guides":
          - "Sui Basic Concepts": cookbook/sui-intro.md
          - "Move Language": cookbook/move.md

      - "Code Snippets":
          - "Example 1": cookbook/test/Subject1.md
          - "Example 2": cookbook/test/Subject2.md
          - "Big Subject":
              - "SubjectSub1": cookbook/test/SubjectSub1.md
              - "SubjectSub2": cookbook/test/SubjectSub2.md
          - "Subject3": cookbook/test/Subject3.md

  - "Sui-Base":
      - "Sui-Base": index.md
      - "Installation": how-to/todo.md
      - "Using Localnet": how-to/todo.md
      - "Using Devnet": how-to/todo.md
      - "Sui-Base Scripts": how-to/scripts.md
      - "Path and Env": reference.md
      - "Rust":
          - "Demo-App": rust/demo-app/README.md
      - "Python":
          - "Some-Example": python/README.md

  - "Community":
      - "Contribute": community.md
      - "External Links": links.md
