[package]
name = "sui-base-helper"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
sui-types = { path = "../../../sui-base/workdirs/active/sui-repo/crates/sui-types/" }
home = "0.5.4"
serde_json = "1.0"
serde_yaml = "0.9"
thiserror = "1.0"
