name: Deploy Website

on:
  #  push:
  #  branches: [main]
  #pull_request:
  #  branches: [main]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  diff:
    runs-on: [ubuntu-latest]
    outputs:
      isDoc: ${{ steps.diff.outputs.isDoc }}
    steps:
      - uses: actions/checkout@v3
      - name: Detect Changes
        uses: "./.github/actions/diffs"
        id: diff

  deploy:
    needs: diff
    if: ${{ (needs.diff.outputs.isDoc == 'true') || (github.event_name == 'workflow_dispatch') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-minify-plugin
      - run: mkdocs gh-deploy --config-file docs/mkdocs.yml --force
