name: Deploy Website

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  diff:
    runs-on: [ubuntu-latest]
    outputs:
      isDoc: ${{ steps.diff.outputs.isDoc }}
    steps:
      - uses: actions/checkout@v3
      - name: Detect Changes
        uses: "./.github/actions/diffs"
        id: diff

  deploy:
    runs-on: ubuntu-latest
    if: needs.diff.outputs.isDoc == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: mkdocs gh-deploy --force
