# Periodic exhaustive tests with latest main branch from Mysten Labs.
#
# This is for early warning of breaking changes while Mysten Labs
# independently modify the Sui client.
#
# Note: the main branch is not same as mainnet branch! The main branch
#       is the cutting edge changes that are to be merge next into
#       Mysten Labs devnet branch.
#

name: nightly tests

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 6 * * *" # every day 5AM

  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Prepare environment
        run: |
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          ln -s $GITHUB_WORKSPACE $HOME/suibase
      - name: Tests with Mysten Labs main branch (cutting edge)
        run: $HOME/suibase/scripts/tests/run-all.sh --main_branch --github_token ${{ secrets.GITHUB_TOKEN }}
