# Done on any changes to Suibase main branch
#
# This is a very quick sanity check that simulate someone
# updating to the latest branch + current pre-built binaries.
#
# Purposely do not install Rust + Sui pre-requesites.
#
# More extensive tests are expected already done on dev branch and nightly.
#
name: Release Tests

# Controls when the workflow will run

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    name: Test ${{ matrix.os }} ${{ matrix.ci_workdir }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout Dev Branch
        uses: actions/checkout@v4

      - name: Sui Prerequesites (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install curl

      - name: Sui Prerequesites (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install curl

      - name: Prepare environment
        run: |
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          ln -s $GITHUB_WORKSPACE $HOME/suibase

      - name: Only sanity tests the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: $HOME/suibase/scripts/tests/run-all.sh --release-tests
