name: Scripts Test Runner

# Controls when the workflow will run
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

  workflow_dispatch:

jobs:
  diff:
    runs-on: [ubuntu-latest]
    outputs:
      isScript: ${{ steps.diff.outputs.isScript }}
    steps:
      - uses: actions/checkout@v3
      - name: Detect Changes
        uses: "./.github/actions/diffs"
        id: diff

  test:
    name: Test on ${{ matrix.os }}
    #needs: diff
    #if: needs.diff.outputs.isScript == 'true'

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Run sui-base tests
        run: |
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          ln -s $GITHUB_WORKSPACE $HOME/sui-base
          $HOME/sui-base/scripts/common/__scripts-tests.sh --github
